name: Minute Empty Commit Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every minute
  # workflow_dispatch:  # Allows manual triggering if needed

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history so pull works correctly

      - name: Set up Git configuration
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"

      - name: Pull latest changes
        run: git pull origin main  # Pulls latest changes from the 'main' branch

      - name: Create an empty commit
        run: |
          git commit --allow-empty -m "Empty commit every minute"

      - name: Push changes
        run: |
          git push origin main  # Replace 'main' with your branch if different
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Uses built-in GitHub token
